name:                functional-interpreter
version:             0.1.0.0
github:              "therewillbecode/functional-interpreter"
license:             MIT
author:              "Tom Chambrier"
maintainer:          "tomw08@gmail.com"
copyright:           "2019 Tom Chambrier"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/therewillbecode/functional-interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- pretty-simple

library:
  source-dirs: src

executables:
  functional-interpreter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-interpreter

tests:
  functional-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functional-interpreter
    - hspec
